config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users
  get 'pages/home'
  get 'pages/work'
  get 'pages/service'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'pages/home'            #vista raiz
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :category_id, :user_id)
    end
end

app/controllers/concerns/turbo_devise_user_controller.rb
class TurboDeviseUserController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
        controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => e
        if get?
        raise e
        elsif has_errors? && default_action
            render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
            redirect_to navigation_location
        end
    end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def work
  end

  def service
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= article.category_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= article.user_id %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo %>
  </div>
  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>
  <div>
    <%= form.label :documento, style: "display: block" %>
    <%= form.file_field :documento %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
    
  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog personal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    
    
    
    
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alert' %>
    <%= yield %>
  </body>
  <footer>
  <p>Realizado por Helmut Cárdenas p.</p>
  </footer>

  
</html>

app/views/pages/contact.html.erb
<h1>Hablemos</h1>

<body>
    <ul>
        <li><a href="#"><i class="fa-brands fa-square-instagram"></i></a></li>
        <li><a href="https://github.com/helmutcardenas" target="_blank"><i class="fa-brands fa-square-github"></i></a></li>
        <li><a href="https://www.linkedin.com/in/helmut-c%C3%A1rdenas-3a8bb9245/" target="_blank"><i class="fa-brands fa-linkedin"></i></a></li>
        <li><a href="https://wa.me/56931450940?text=Hola+¿como+estás?" target="_blank"><i class="fa-brands fa-square-whatsapp"></i></a></li>
    </ul>
</body>

app/views/pages/home.html.erb
<h1>Bienvenidos</h1>
<br>
<h2>
Hi, I´m Helmut, Web Developer.
</h2>

<div class="contenedor">
        <figure>
            <%= image_tag 'mockup5.jpg' %>
            <div class="capa">
                <h3><strong>Proyect 01</strong></h3>
                <br>
                <p><strong> LICITALO.CL es una plataforma donde personas como tu o como yo que buscan algun producto se contacten con proveedores que te pueden ofrecer sus precios y TÚ podrás elegir el precio que mas te conviene. Si necesitas un servicio también puedes cotizar por LICITALO.CL, los prestadores de servicios atenderán tu requerimiento entregando un valor que tú decidiras aceptar o rechazar.</strong></p>
            </div>
        </figure>
    </div>

app/views/pages/service.html.erb
<h1>¿Qué podemos hacer?</h1>

app/views/pages/work.html.erb
<h1>Portafolio</h1>
<br><br>
<h3>Te presento algunos Mockup´s de distintas propuestas, luego de realizar seguimiento al cliente sobre las necesidades de su Producto Digital. Luego de producir estas propuestas, corregir algunos puntos junto al cliente, se inicia el proceso de programación para que estas páginas cobren vida.</h3>
<br><br>

<%= image_tag 'mockup5.jpg' %>

app/views/shared/_alert.html.erb
<% if notice %>
<div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>
<% if alert %>
<div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<nav class="be-red white large-padding">
    <ul>
        <ul class="col-md">
        <ul><%= link_to 'Inicio', root_path %></ul>
        </ul>
        <ul class="col-md">
        <ul><%= link_to 'Articulos', articles_path %></ul>
        </ul>
        <ul class="col-md">
        <ul><%= link_to 'Servicios', pages_service_path %></ul>
        </ul>
        <ul class="col-md">
        <ul><%= link_to 'Portafolio', pages_work_path %></ul>
        </ul>
        <ul class="col-md">
        <ul><%= link_to 'Contacto', pages_contact_path %></ul>
        </ul>
    </ul>
</nav>